import { pgTable, text, uuid, index, unique } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { timestamptz, createdAtCol } from './common';

/**
 * Desktop Auth Codes
 *
 * Short-lived, single-use codes generated by the backend and redeemed by the
 * desktop app via the loopback callback.
 *
 * Security:
 * - Store ONLY a hash of the code (never plaintext)
 * - Codes are short-lived and single-use
 */
export const desktopAuthCodes = pgTable(
  'desktop_auth_codes',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    codeHash: text('code_hash').notNull(),
    clerkUserId: text('clerk_user_id').notNull(),
    deviceName: text('device_name'),
    createdAt: createdAtCol(),
    expiresAt: timestamptz('expires_at').notNull(),
    usedAt: timestamptz('used_at'),
  },
  (table) => [
    unique('desktop_auth_codes_code_hash_unique').on(table.codeHash),
    index('desktop_auth_codes_clerk_user_id_idx').on(table.clerkUserId),
    index('desktop_auth_codes_expires_at_idx').on(table.expiresAt),
  ],
);

export type DesktopAuthCode = typeof desktopAuthCodes.$inferSelect;
export type NewDesktopAuthCode = typeof desktopAuthCodes.$inferInsert;

/**
 * Desktop Sessions
 *
 * Long-lived refresh sessions for desktop devices.
 *
 * Security:
 * - Store ONLY hashes of refresh tokens (never plaintext)
 * - Rotate refresh tokens on every refresh
 * - Keep a short grace window for the previous hash to tolerate races
 */
export const desktopSessions = pgTable(
  'desktop_sessions',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    clerkUserId: text('clerk_user_id').notNull(),
    refreshTokenHash: text('refresh_token_hash').notNull(),
    refreshTokenHashPrev: text('refresh_token_hash_prev'),
    refreshTokenPrevExpiresAt: timestamptz('refresh_token_prev_expires_at'),
    deviceName: text('device_name'),
    createdAt: createdAtCol(),
    lastUsedAt: timestamptz('last_used_at'),
    expiresAt: timestamptz('expires_at').notNull(),
    revokedAt: timestamptz('revoked_at'),
  },
  (table) => [
    unique('desktop_sessions_refresh_token_hash_unique').on(table.refreshTokenHash),
    index('desktop_sessions_clerk_user_id_idx').on(table.clerkUserId),
    index('desktop_sessions_expires_at_idx').on(table.expiresAt),
    index('desktop_sessions_revoked_at_idx').on(table.revokedAt),
  ],
);

export type DesktopSession = typeof desktopSessions.$inferSelect;
export type NewDesktopSession = typeof desktopSessions.$inferInsert;
