export function LogoMark({ className }: { className?: string }) {
  return (
    <svg
      viewBox="-4 -4 104 118"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      focusable="false"
    >
      <line
        x1="48"
        y1="5"
        x2="70.71"
        y2="41.5"
        stroke="currentColor"
        strokeWidth="10"
        strokeLinecap="round"
      />
      <line
        x1="91.3"
        y1="30"
        x2="70.71"
        y2="68.5"
        stroke="currentColor"
        strokeWidth="10"
        strokeLinecap="round"
      />
      <line
        x1="91.3"
        y1="80"
        x2="48"
        y2="80"
        stroke="currentColor"
        strokeWidth="10"
        strokeLinecap="round"
      />
      <line
        x1="48"
        y1="105"
        x2="25.29"
        y2="68.5"
        stroke="currentColor"
        strokeWidth="10"
        strokeLinecap="round"
      />
      <line
        x1="4.7"
        y1="80"
        x2="25.29"
        y2="41.5"
        stroke="currentColor"
        strokeWidth="10"
        strokeLinecap="round"
      />
      <line
        x1="4.7"
        y1="30"
        x2="48"
        y2="30"
        stroke="currentColor"
        strokeWidth="10"
        strokeLinecap="round"
      />
    </svg>
  );
}

