import type { AuthVariables } from '@/auth/types';
import type { Database, DatabaseTx } from '@/db';

// Bindings are auto-generated from wrangler.jsonc via: pnpm cf-typegen
// Additional secrets are typed from .dev.vars (local) and .dev.vars.example (documentation)
// Cloudflare.Env is the interface generated by wrangler types from worker-configuration.d.ts
export type Bindings = Cloudflare.Env & {
  FTP_JWT_SECRET: string;
  FTP_JWT_SECRET_PREVIOUS?: string;
  DESKTOP_ACCESS_JWT_SECRET: string;
  DESKTOP_REFRESH_TOKEN_PEPPER: string;
};

export type Variables = AuthVariables & {
  db: () => Database; // HTTP adapter - fast, no transactions
  dbTx: () => DatabaseTx; // WebSocket adapter - with transaction support
};

export type Env = { Bindings: Bindings; Variables: Variables };
